// <auto-generated />
namespace Eshop.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class miguserorderwish : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(miguserorderwish));
        
        string IMigrationMetadata.Id
        {
            get { return "201809091153099_mig-user-order-wish"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
